### ISSUE TITLE
module start failure

### ISSUE THREAD

**Issue by dvescovi1** [gbbiotwesouth/noderededgemodule#7]
I have been trying to run through the example on my iMX8 linux device.
I am building the yocto image with iot edge build in.
The IoT Edge run time (1.08 Arm64) appears to be working fine and the simulated temperature module is getting deployed from Azure IoT Hub and also appears to be working.
I tried adding the noderededgemodule from docker hub (iotblackbelt/noderededgemodule:1.0.2-arm64v8).
I set the routes and create settings.
I created the /node-red directory on the device and the module seems to be downloading but it always indicate "RUNTIME STATUS" "backoff" in the Azure portal and
```
root@imx8mmidpi:~# iotedge list
NAME                        STATUS           DESCRIPTION               CONFIG
nodered                     failed           Failed (1) 2 minutes ago  iotblackbelt/noderededgemodule:1.0.2-arm64v8
edgeHub                     running          Up an hour                mcr.microsoft.com/azureiotedge-hub:1.0
SimulatedTemperatureSensor  running          Up an hour                mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent                   running          Up an hour                mcr.microsoft.com/azureiotedge-agent:1.0
```
in the iotedge status. I am not sure how to proceed or debug.
Any ideas?

**Comment by dvescovi1** [comment]
I was able to pull the container logs 
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--cache',
1 verbose cli   '/data/.npm',
1 verbose cli   '--',
1 verbose cli   '--userDir',
1 verbose cli   '/data'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose config Skipping project config: /usr/src/node-red/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle node-red-docker@1.1.3~prestart: node-red-docker@1.1.3
7 info lifecycle node-red-docker@1.1.3~start: node-red-docker@1.1.3
8 verbose lifecycle node-red-docker@1.1.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle node-red-docker@1.1.3~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle node-red-docker@1.1.3~start: CWD: /usr/src/node-red
11 silly lifecycle node-red-docker@1.1.3~start: Args: [
11 silly lifecycle   '-c',
11 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"'
11 silly lifecycle ]
12 silly lifecycle node-red-docker@1.1.3~start: Returned: code: 1  signal: null
13 info lifecycle node-red-docker@1.1.3~start: Failed to exec start script
14 verbose stack Error: node-red-docker@1.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:315:20)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:315:20)
14 verbose stack     at maybeClose (internal/child_process.js:1021:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
15 verbose pkgid node-red-docker@1.1.3
16 verbose cwd /usr/src/node-red
17 verbose Linux 5.4.24-2.1.0+gbabac008e5cf
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--cache" "/data/.npm" "--" "--userDir" "/data"
19 verbose node v12.18.3
20 verbose npm  v6.14.6
21 error code ELIFECYCLE
22 error errno 1
23 error node-red-docker@1.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
23 error Exit status 1
24 error Failed at the node-red-docker@1.1.3 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by dvescovi1** [comment]
fixed the permission issue by doing chmod 777 /node-red
now all modules are starting and running and continue to run after deploying flow.

**Comment by dvescovi1** [comment]
now when I deploy flow I get a "Flow stopped due to missing node type moduleclient."
Any idea what this is about?

**Comment by ghost** [comment]
You have to udpate the node in "palett manager" ,, delete the example flows, restart ( because the update requires it), then import example flow again.

**Comment by dvescovi1** [comment]
I was able to figure that one out. I got  a bit farther but not hitting a NoderedModule failure.
I get the following from the log:
```> node-red-docker@1.1.3 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
23 Oct 19:00:10 - [info]
Welcome to Node-RED
===================
23 Oct 19:00:10 - [info] Node-RED version: v1.1.3
23 Oct 19:00:10 - [info] Node.js  version: v12.18.3
23 Oct 19:00:10 - [info] Linux 5.4.24-2.1.0+gbabac008e5cf arm64 LE
23 Oct 19:00:11 - [info] Loading palette nodes
23 Oct 19:00:14 - [info] Dashboard version 2.23.4 started at /ui
23 Oct 19:00:14 - [info] Settings file  : /data/settings.js
23 Oct 19:00:14 - [info] Context store  : 'default' [module=memory]
23 Oct 19:00:14 - [info] User directory : /data
23 Oct 19:00:14 - [warn] Projects disabled : editorTheme.projects.enabled=false
23 Oct 19:00:14 - [info] Flows file     : /data/flows.json
23 Oct 19:00:14 - [info] Server now running at http://127.0.0.1:1880/
23 Oct 19:00:14 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
23 Oct 19:00:14 - [info] Starting flows
23 Oct 19:00:14 - [info] Started flows
23 Oct 19:00:14 - [info] [edgeclient:eb320c80.46108] Module Client created.
23 Oct 19:00:15 - [info] [edgeclient:eb320c80.46108] Module Client open error:UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.3:8883 error
23 Oct 19:00:15 - [red] Uncaught Exception:
23 Oct 19:00:15 - UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.3:8883 error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-docker@1.1.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /data/.npm/_logs/2020-10-23T19_00_15_162Z-debug.log
> node-red-docker@1.1.3 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
```

Any idea what might be going on?

**Comment by ghost** [comment]
it apperas there is something wrong with the mqtt communication. 
have you done any configuration of node-red ? 

 i would suggest delete/move  the flow json from the /node-red fodler and start again, as it was probalby something misconfigured when it was imported.  

have you done any other configuraton related to security or jsut following the example form this github readme ? 

I just installed and have it running on a rpi 4.   
i had to chmod 777 as you did, then i updated node, restarted everything and then imported example flow. 

i am also running EdgeAgent and EdgeHub version 1.0.10 ( do not think that matters)

**Comment by dvescovi1** [comment]
I did not do any configuration. I was going to try on my raspberry pi but having some other start up issues (not related).
I am using on a iMX8 ARM64 based device. It is using 1.0.8.

**Comment by ghost** [comment]
i think it has to do with the order something was installed. 

i would suggest deleting the /node-red folder and start again. 
* Create folder
*chmod 777 on folder
*start node-red
* go to palett maanger and update azure iot node. 
*restart module/device
*import example flow . 

then it should be running. 

the error you get has to do with acces and that the node does not handle that "correctly" and crashes node-red instead.
i am sure if you could starte node-red in safe mode, it would start fine, as it is the "azure node" that appears to be wrongly configured and therfore crashes ,  unfortinaly  the way this node work you can not change the "confgiuration" manually"  and that is why i suggest starting again.

**Comment by dvescovi1** [comment]
I now have my raspberry pi device working fine.
iiMX8 device still has problems. I can clean node-red folder and redeploy NoderedModule and everything seems to start fine. It is only when I deploy flows that it crashes.

**Comment by dvescovi1** [comment]
I see nothing is written to /node-red folder ether.

**Comment by ghost** [comment]
yes, because when you deploy it tires to save the configuration and something is wrong , resulting in the problem. 

it might have to do with how the edge is installed on the MX8 vs raspberry and that there is some acces permitions that are not the same,  that the edge envrionment was installed as root, while the  module environment runs as user etc.  and that the node package expect something to be a certan way to work. 

this is outside what i am able to help with , unfortunately.

**Comment by dvescovi1** [comment]
So now raspberry pi with arm32 module seems to be working fine.
imx8 with arm64 module has issues with deploy flow.
running iotedge 1.0.8 and using iotblackbelt/noderededgemodule:1.0.2-arm64v8 for the imx8
running iotedge 1.0.8 and using iotblackbelt/noderededgemodule:1.0.2-arm32v7 for pi

**Comment by dvescovi1** [comment]
another strange thing ... even on the working raspberry pi device (which is updating and ui working) there is also nothing in the /node-red folder
What is up with that?

**Comment by ghost** [comment]
the nod-red folder you are talking aobut are at root level ? not in a subfolder etc ? 



i have data in my folders. 
![image](https://user-images.githubusercontent.com/63996627/97308336-0e8dcb00-1861-11eb-936c-0dd14e949244.png)

**Comment by ghost** [comment]
you have done this option ? and not changed the path here ? 

the bind is where you map /node-red folder on the system to the container /data folder, so that data is stored and not deleted when restarted ? 

because if that folder is not mapped, node-red  data will be stored inside the container. and it will dissapear when restarted


![image](https://user-images.githubusercontent.com/63996627/97308634-60365580-1861-11eb-95ac-552bafc23096.png)

**Comment by dvescovi1** [comment]
yup everything there in the deployment:
![image](https://user-images.githubusercontent.com/1312052/97310459-a24ba100-1839-11eb-8995-fb4fd5199066.png)


![image](https://user-images.githubusercontent.com/1312052/97310940-30c02280-183a-11eb-951b-2330bbd9ee54.png)

**Comment by dvescovi1** [comment]
![image](https://user-images.githubusercontent.com/1312052/97311066-564d2c00-183a-11eb-9b8e-bfb922fb2af3.png)

**Comment by oivheg** [comment]
You have changed the container folder .

You have changed it to node-red 

It should still be /data
Not node-red:node-red as you have. 
But node-red:/data

**Comment by dvescovi1** [comment]
looks like github repo needs a PR ... still shows:
```          "modules": {
            "NoderedModule": {
              "version": "1.0",
              "type": "docker",
              "status": "running",
              "restartPolicy": "always",
              "settings": {
                "image": "iotblackbelt/noderededgemodule:1.0.0-arm32v7",
                "createOptions": "{\"HostConfig\": {\"Privileged\": true,\"Binds\":[\"/node-red:/node-red\"],\"PortBindings\": {\"1880/tcp\": [{\"HostPort\": \"1880\"}]}}}"
              }
            },
```

both version and Binds appear to be wrong

**Comment by ghost** [comment]
I suggest you follow the readme and add that module trough the portal to the device.   And when it is up an running. Check the edge device twin and see how it is configured.  You then might se anything different .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dvescovi1** [comment]
I know you can deploy and configure via the Azure portal but I prefer to do everything from VS code

**Comment by ghost** [comment]
Yes , i was just suggesting to do that to get it up an running and se how it is configured , so you can see if that helps in your deployment, as missing data In node-red folder means it is most likely misconfigured , as I know it works when configured from the
portal .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dvescovi1** [comment]
Container create option as seen from portal also showing correct mapping  "/node-red:/data"
raspberry pi all working fine.
iMX8 still crashes as soon a I press "deploy" flow.
I even tried with no "Binds" at all:
```
{
  "HostConfig": {
    "Privileged": true,
    "PortBindings": {
      "1880/tcp": [
        {
          "HostPort": "1880"
        }
      ]
    }
  }
}
```
 and it still fails on flow deployment.

I then tried with arm32v7 instead of arm64v8 ... same problem.

**Comment by dvescovi1** [comment]
out of desperation I even tried to copy the working flows.json from the pi device to the imx8 device and restart everything ... still crashes the same way

**Comment by oivheg** [comment]
Then we are back to one of the first problems , I assume .

Where node-red flow  fails because authentication with the edge environment
fails .  So it might have to do with how the edge environment have been
installed on the device.  Have it been installed as a privileged user or
not ?

So there is most likely som environmental differences in how the mx device
runs, compared to the rpi .





MVH
Øivind Heggland
oivheg@gmail.com
92627034

**Comment by dvescovi1** [comment]
I totally agree with your assessment and I have been trying to find out just what the difference is. At first thought it might have to do with the fact my iMX8 device is built with yocto distro and only contains a basic components. It does not include a browser as it is built as a headless device ... as opposed to raspberry pi which does have a browser and looks more like a full fledge desktop. But I was told not so, there are plenty of headless devices doing this same thing. The actual Azure iot edge component is a direct implementation of MS code just wrapped in a yocto recipe by NXP. Both the raspberry pi and my device are running the same version (1.0.8) but yes they are installed differently. pi uses the built debian package and installed with the apt-get install command whereas iMX8 uses the yocto recipe. There is obviously some difference in the underlying dependencies or permissions.

**Comment by dvescovi1** [comment]
so I found this interesting ... the iotedge runs as a service under linux so I dumped the service status both of my device and pi ... I do see a difference:
my device:

![image](https://user-images.githubusercontent.com/1312052/97428665-b1d7f200-18ec-11eb-880c-57128ee721bd.png)
  
pi:
![image](https://user-images.githubusercontent.com/1312052/97428706-c1573b00-18ec-11eb-966a-ab1bc892e300.png)

looks suspicious! 


and docker service status
my device:
![image](https://user-images.githubusercontent.com/1312052/97429693-3119f580-18ee-11eb-90c1-c08da7a2204b.png)

and pi:

![image](https://user-images.githubusercontent.com/1312052/97429762-3ecf7b00-18ee-11eb-8c6f-e7c368201e19.png)

**Comment by dvescovi1** [comment]
also for what its worth I see a "flows_cred.json" file created in the /node-red folder on my device just before it crashes. Do not see same on raspberry pi device.

**Comment by dvescovi1** [comment]
closing this issue and opening another with complete logs.
